config/routes.rb
Chat::Application.routes.draw do
  get "log_out" => "sessions#destroy", as: "log_out"
  get "log_in" => "sessions#new", as: "log_in"
  get "sign_up" => "users#new", as: "sign_up"
  root :to => "sessions#new"
  namespace :ajax do
    resources :messages
    resource :chat, only: :show
  end
  resources :users, only: [:index, :new, :create]
  resources :chat_rooms, only: :index
  resources :sessions, only: [:new, :create, :destroy]

  namespace :comet do
    resources :messages
  end

end

app/models/message.rb
class Message < ActiveRecord::Base
  attr_accessible :message_text, :user
  belongs_to :user

  scope :latest_posts, lambda{ |last_visit| where('created_at > ?', last_visit) }
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password, :password_confirmation
  
  attr_accessor :password
  before_save :encrypt_password
  
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email

  TIME_ONLINE = 5.minutes

  scope :online, lambda{ where('updated_at > ?', TIME_ONLINE.ago) }

  def self.authenticate(email, password)
    user = find_by_email(email)
    user if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
  end

  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end

end

app/controllers/ajax/chats_controller.rb
class Ajax::ChatsController < ApplicationController
  include TrackLastVisit
  before_filter :authenticate

  def show
  end
end

app/controllers/ajax/messages_controller.rb
class Ajax::MessagesController < ApplicationController
  include TrackLastVisit
  before_filter :authenticate

  def index
    @messages = Message.latest_posts(current_user.updated_at)
  end

  def create
    @message = Message.create(message_text: params[:message][:message_text], user: current_user)
  end
end

app/controllers/ajax_chat_controller.rb
class AjaxChatController < ApplicationController
  before_filter :authenticate
  before_filter :messages_all, :only => [:index, :messages]
  after_filter :last_update, :only => [:index, :messages]

  def index
  end

  def new
    @message = Message.new
  end

  def create
    @message = Message.new(:message_text => params[:message][:message_text], :user => current_user)
    if @message.save
      messages_all
    end
  end

  def messages
  end

  private
  def messages_all
    if compare_last_message_and_last_update?
      last_message_time = Time.zone.parse(cookies[:last_update]).utc
      @messages = Message.where('created_at > ?', last_message_time.to_s)
    else
      @messages = []
    end
  end

  def last_update
    message_last_create = Message.select(:created_at).first
    if compare_last_message_and_last_update?
      cookies[:last_update] = message_last_create.created_at
      p cookies[:last_update]
    else
      cookies[:last_update] = Time.now
    end
  end

  def compare_last_message_and_last_update?
    message_last_create = Message.select(:created_at).first
    if message_last_create and cookies[:last_update]
      message_last_create.created_at.to_i > cookies[:last_update].to_time.to_i
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user

  private
  def current_user
    @current_user ||= session[:user_id] && User.find_by_id(session[:user_id])
  end

  helper_method :current_user

  def authenticate
    logged_in? || access_denied
  end

  def logged_in?
    current_user.is_a? User
  end

  helper_method :logged_in?

  def access_denied
    redirect_to :log_in
  end

end

app/controllers/chat_rooms_controller.rb
class ChatRoomsController < ApplicationController
  before_filter :authenticate, :only => :index
  def index
  end
end

app/controllers/comet/messages_controller.rb
class Comet::MessagesController < ApplicationController
  include TrackLastVisit
  before_filter :authenticate

  def index
    @messages = Message.latest_posts(current_user.updated_at)
  end

  def create
    @message = Message.create(message_text: params[:message][:message_text], user: current_user)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.authenticate(params[:email], params[:password])
    if user
      session[:user_id] = user.id
      redirect_to :chat_rooms, :notice => "Logged in!"
    else
      flash.now.alert = "Invalid email or password"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Logged out!"
  end

end

app/controllers/track_last_visit.rb
module TrackLastVisit
  def self.included(klazz)
    klazz.send(:after_filter, :track, except: :create)
  end

  def track
    current_user.touch
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.online
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to root_url, :notice => "Signed up!"
    else
      render "new"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def broadcast(channel, &block)
    message = {:channel => channel, :data => capture(&block), :ext => {:auth_token => FAYE_TOKEN}}
    uri = URI.parse("http://localhost:9292/faye")
    Net::HTTP.post_form(uri, :message => message.to_json)
  end
end

app/views/ajax/chats/_new.html.erb
<%= form_for(:message, url: { action: 'create', controller: 'ajax/messages' }, remote: true) do |f| %>
  <div>
    <%= f.text_field :message_text, class: "message_text" %>
    <%= f.submit "Send Message"%>
  </div>
<% end %>

app/views/ajax/chats/show.html.erb
<div id="ajax_chat">
</div>

<div id="bottomPanel">
  <%= render "new" %>
</div>

<div id="users_online">
</div>

app/views/ajax/messages/_messages.html.erb
<% @messages.each do |message| %>
<div>
  <%= message.created_at.strftime('%X') %>
  <%= message.user.email %>
  <%= message.message_text %>
</div>
<% end %>

app/views/ajax/messages/_new.html.erb
<%= form_for(:message, :url => { :action => 'create' }, :remote => true) do |f| %>
  <div>
    <%= f.text_field :message_text, class: "message_text" %>
    <%= f.submit "Send Message"%>
  </div>
<% end %>

app/views/ajax/messages/create.js.erb
$(".message_text").val("");

app/views/ajax/messages/index.html.erb
<div id="ajax_chat">
</div>

<div id="bottomPanel">
  <%= render 'new' %>
</div>

<div id="users_online">
</div>

app/views/ajax/messages/index.js.erb
$('#ajax_chat').append("<%= escape_javascript render 'messages' %>").scrollTop(9999);

app/views/chat_rooms/index.html.erb
<h2>Chat room</h2>
<ul>
  <li><%= link_to "Ajax Chat", ajax_chat_path %></li>
  <li><%= link_to "Comet Chat", comet_messages_path %></li>
  <li><%= link_to "WS Chat"%></li>
</ul>

app/views/comet/messages/_message.html.erb
<p><%= message.created_at.strftime('%X') %>
<%= message.user.email %>
<%= message.message_text %></p>

app/views/comet/messages/create.js.erb
<% broadcast "/comet/messages/new" do %>
$("#comet_chat").append("<%= escape_javascript render(@message) %>").scrollTop(9999);
<% end %>
$("#message_text").val("");

app/views/comet/messages/index.html.erb
<div id="comet_chat">
  <%= render @messages %>
</div>

<div id="bottomPanel">
  <%= form_for Message.new, :url => {:action => 'create'}, :remote => true do |f| %>
    <%= f.text_field :message_text, id: "message_text" %>
    <%= f.submit "Send" %>
  <% end %>
</div>

<div id="users_online">
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Chat</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application", "http://localhost:9292/faye.js" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="sign_in">
  <% if current_user %>
    Logged in as <%= current_user.email %>.
    <%= link_to "Log out", log_out_path %>
  <% else %>
    <%= link_to "Sign up", sign_up_path %> or
    <%= link_to "log in", log_in_path %>
  <% end %>
</div>

<% flash.each do |name, msg| %>
  <%= content_tag :div, msg, :id => "flash_#{name}" %>
<% end %>
<%= yield %>

</body>
</html>

app/views/users/_users.html.erb
<% @users.each do |user| %>
  <p><%= user.email %></p>
<% end %>

app/views/users/index.js.erb
$('#users_online').html('<%= escape_javascript render "users" %>').scrollTop(9999);

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </p>
  <p class="button"><%= f.submit %></p>
<% end %>